apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xxkx8jp9g-python
  janus-idp.io/tekton: xxkx8jp9g-python
  backstage.io/kubernetes-id: xxkx8jp9g-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xxkx8jp9g-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
